@@startuml
    class OrdemDeManutencao{
        Long numeroDaOrdem
        String LocalDaOrdem
        int codigoEquipamento
        String pecaDeTroca
        boolean statusOrdemDeServico
    }

    class Local {
        int codLocal
        String nomeLocal
        boolean tipoLocal
        int car
        String enderecoLocal
    }

    class Peca {
        int codPeca
        String nomePeca
        int quantidadePeca
        double valorPeca
        String dataDeEntrada
    }
@@enduml